services:
  server:
    build:
      context: "./"
    volumes:
      - "./src:/app"
    ports:
      - "${SERVER_PORT}:5000"
    env_file:
      - ".env"
    tty: true

  db:
    image: mysql:8.0.30
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - "db_data:/var/lib/mysql"
      - "./my.conf:/etc/mysql/conf.d/my.cnf"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Tokyo

volumes:
  db_data:
